### ISSUE TITLE
Is https://gltfapi.co/ down?

### ISSUE THREAD

**Issue by pjcozzi** [headjack-dev/gltf-api#1]
It doesn't seem to load right now.  Thanks!  Just wanted to tweet it to the world! 😃

**Comment by nickkraakman** [comment]
Hi @pjcozzi,

Thanks for pointing this out!

Just restarted the Docker container and things are back to normal again. Really appreciate a tweet :-)

**Comment by pjcozzi** [comment]
Cool, thanks, will tweet now!

**Comment by spencercap** [comment]
is the site down again?

**Comment by nickkraakman** [comment]
@spencercap it may have been a temporary issue. The site is up now.

**Comment by spencercap** [comment]
rad, thanks!

**Comment by Denny2016** [comment]
is the site down again?

**Comment by grycyk** [comment]
Seeing a 500 on https://gltfapi.co
